### ISSUE TITLE
Implement "Stage" System

### ISSUE THREAD

**Issue by Superxpdude** [Superxpdude/tmtm_template#15]
Task for implementing the stage system.
The stage system would affect respawning, loadouts, etc.
Would allow for missions that have objectives like "Acquire better weapons", while maintaining compatibility with the loadout system.

## TODO

- [x] Stage Initialization Function
- [x] Stage Update Function
- [x] Stage Configs
- [x] Support in the template loadout framework
